function Letter(x,y,lett)
{
  this.x=x;
  this.y=y;
  this.lett=lett;
  this.acc=.4;
  this.speed=2;
  this.display=function()
  {
    textAlign(CENTER);
    textSize(40);
    fill(255,255,0);
    strokeWeight(7);
    stroke(0);
    text(lett,this.x,this.y);
    strokeWeight(1);
  }
  this.move=function()
  {
    this.y-=this.speed;
    this.speed+=this.acc;
  }
}
